//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Web_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string tokenid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string corpname { get; set; }
        public string phone { get; set; }
        public string localphone { get; set; }
        public string direction { get; set; }
        public string email { get; set; }
        public string pubkey { get; set; }
        public string subkey { get; set; }
        public int cantusers { get; set; }
        public int controlusers { get; set; }
        public Nullable<System.DateTime> singupdate { get; set; }
        public Nullable<System.DateTime> expireddate { get; set; }
    }
}
